# Generated by Django 4.2.11 on 2024-06-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
